apiVersion: v2
version: 1.0.0
name: proxy-chart
description: A proxy-chart to the global-chart

dependencies:
  - name: global-chart
    repository: https://github.com/danielmarom78/cd-repo-demo.git
    version: '>=0-0'
    alias: application



