apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-cd
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/tal-hason/cd-repo-demo.git
      revision: main
      directories:
      - path: "gitea-deployment/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: gitea
      source:
        repoURL: https://github.com/tal-hason/cd-repo-demo.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: gitea
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true