kind: Gitea
apiVersion: pfe.rhpds.com/v1
metadata:
  name: gitea-demo
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  giteaSsl: true
  giteaAdminUser: opentlc-mgr
  giteaAdminPassword: ""
  giteaAdminPasswordLength: 32
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaCreateUsers: true
  giteaGenerateUserFormat: "user%d"
  giteaUserNumber: 2
  giteaUserPassword: openshift
  giteaMigrateRepositories: true
  giteaWebhookAllowedHostList: '*'
  giteaWebhookSkipTlsVerify: true
  giteaRepositoriesList:
  - repo: https://github.com/danielmarom78/cd-repo-demo.git
    name: cd-repo-demo
    private: false
  - repo: https://github.com/danielmarom78/nodejs-demo-app.git
    name: nodejs-demo-app
    private: false
  - repo: https://github.com/danielmarom78/angular-demo-app.git
    name: angular-demo-app
    private: false
  - repo: https://github.com/danielmarom78/dotnet-demo-app.git
    name: dotnet-demo-app
    private: false