apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ngnix-api-gateway-workshop-git-
spec:
  params:
    - name: APP_NAME
      value: demo
    - name: GIT_REPO
      value: 'https://github.com/tal-hason/nodejs-demo-app.git'
    - name: GIT_REVISION
      value: main
    - name: IMAGE_NAME
      value: quay.io/thason/gitops-demo
    - name: PATH_CONTEXT
      value: .
    - name: IMAGE_TAG
      value: node_v2
    - name: GIT_CD_REPO
      value: 'https://github.com/danielmarom78/cd-repo-demo.git'
    - name: BUILD
      value: 'True'
    - name: DEPLOY_ENV
      value: develop
    - name: SERVICE_NAME
      value: frontend
  pipelineRef:
    name: ngnix-api-gateway-workshop-git
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: pipeline