---
# Source: proxy-chart/charts/application/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '-backend-release-name'
  labels:
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/part-of: release-name
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: dotnet
  annotations:
    route.openshift.io/termination: edge 
    route.openshift.io/destination-ca-certificate-secret: backend-ca-cert
spec:
  rules:
  - host: backend--.cluster-2mbd4.dynamic.redhatworkshops.io
    http:
      paths:
      - backend:
          service:
            name: '-backend-release-name'
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - {}
