apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: prod-backend-app1
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: demo
    app.kubernetes.io/part-of: demo
    app.openshift.io/runtime: dotnet
  name: prod-backend-app1
  namespace: prod
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: prod-backend-app1
    app.kubernetes.io/name: demo
  type: ClusterIP
