---
# Source: proxy-chart/charts/application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: '-websrv-release-name'
  labels:
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/part-of: release-name
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: nodejs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
