apiVersion: v1
data:
  application.properties: '## Properties go here'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: demo-frontend-prod-app1
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: demo
    app.kubernetes.io/part-of: demo
    app.openshift.io/runtime: dotnet
  name: demo-frontend
  namespace: prod