---
# Source: proxy-chart/charts/application/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: 'prod-websrv-proj2-app1'
  labels:
    app.kubernetes.io/name: proj2-app1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/part-of: proj2-app1
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: nodejs
data:
  'application.properties': |-
    ## Properties go here
