apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-cd-initandqa
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/danielmarom78/cd-repo-demo.git
      revision: main
      files:
      - path: "Application/*/qa/values-*.yaml" #example: Application/app1/values-frontend  
      - path: "Application/*/int/values-*.yaml"   
      values:
        applicationName: '{{path[1]}}'
        environment: '{{path[2]}}'

  template:
    metadata:
      name: '{{values.environment}}-{{global.serviceName}}-{{values.applicationName}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/danielmarom78/cd-repo-demo.git
        targetRevision: main
        path: '{{path[0]}}'
        helm:
          parameters:
           - name: global.namespace
             value: '{{values.environment}}'
           - name: global.nameOverride
             value: '{{values.applicationName}}'
          valueFiles:
          - '{{path[1]}}/{{path[2]}}/{{path.filename}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{values.environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
