apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-cd-prod
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/danielmarom78/cd-repo-demo.git
      revision: Production
      directories:
      - path: "*/*" #example: app1/frontend  
      values:
      - applicationName: '{{path[0]}}'
      - serviceName: '{{path[1]}}'
  template:
    metadata:
      name: 'prod-{{serviceName}}-{{applicationName}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/danielmarom78/cd-repo-demo.git
        targetRevision: Production
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
